#!/usr/bin/env zsh

alias path='echo -e ${PATH//:/\\n}'
alias now='date +"%T"'
alias nowtime=now
alias nowdate='date +"%d-%m-%Y"'

alias vi=vim

alias top='htop'

alias ibrew='arch -x86_64 /usr/local/bin/brew'
